<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Pathoschild.TheLongDarkMods.AutoFillMapOnExplore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\MelonLoader\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(ManagedPath)\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(ManagedPath)\Il2CppSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>$(ManagedPath)\Il2CppSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(GamePath)\MelonLoader\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnhollowerBaseLib">
      <HintPath>$(ManagedPath)\UnhollowerBaseLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ModSettings">
      <HintPath>$(ModsPath)\ModSettings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ManagedPath)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(ManagedPath)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy Condition="Exists('$(ModsPath)')" SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)" />
    <Copy Condition="Exists('$(ReleasesPath)')" SourceFiles="$(TargetPath)" DestinationFolder="$(ReleasesPath)" />
  </Target>
</Project>
