<Project>
  <!-- common build settings -->
  <PropertyGroup>
    <!-- metadata -->
    <Authors>Pathoschild</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Pathoschild/TheLongDarkMods</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- build options -->
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>embedded</DebugType>

    <!-- directory paths -->
    <GamePath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</GamePath>
    <ManagedPath>$(GamePath)\MelonLoader\Managed</ManagedPath>
    <ModsPath>$(GamePath)\Mods</ModsPath>
    <ReleasesPath>$(MSBuildThisFileDirectory)\..\_releases</ReleasesPath>
  </PropertyGroup>

</Project>
